PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
CONSTRUCT {
    ?gndConcept rdf:type ?wdType .
    ?gndConcept wdt:P31 ?wdType .
    ?gndConcept rdfs:label ?name .
    ?gndConcept schema:description ?description .
    ?gndConcept owl:sameAs ?gnd .
}

WHERE {
    ?gndConcept wdt:P227 ?gndId .
    ?gndConcept wdt:P31 ?wdType .
    ?gndConcept rdfs:label ?name .
    ?gndConcept schema:description ?description .
    BIND(URI(CONCAT("https://d-nb.info/gnd/", ?gndId)) as ?gnd)
    FILTER (LANG(?name) = "en")
    FILTER (LANG(?description) = "en")
}
