PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
CONSTRUCT {
    ?gndConcept rdf:type ?wdType .
    ?gndConcept wdt:P31 ?wdType .
    ?gndConcept rdfs:label ?name .
    ?gndConcept schema:description ?description .
    ?gndConcept owl:sameAs ?gnd .
    ?gndConcept ?predicate ?additionalProperty .
}

WHERE {
    ?gndConcept wdt:P227 ?gndId .
    ?gndConcept wdt:P31 ?wdType .
    ?gndConcept rdfs:label ?name .
    OPTIONAL {
        VALUES ?predicate {
            wdt:P1476
            wdt:P1680
            wdt:P18
            wdt:P2096
            wdt:P569
            wdt:P570
            wdt:P571
            wdt:P576
            wdt:P577
            wdt:P580
            wdt:P582
            wdt:P585
            wdt:P625
        }
        ?gndConcept ?predicate ?additionalProperty .
    }
    FILTER (LANG(?name) = "en")
    BIND(URI(CONCAT("https://d-nb.info/gnd/", ?gndId)) as ?gnd)
    OPTIONAL { ?gndConcept schema:description ?desc_en . FILTER (LANG(?desc_en) = "en") }
    OPTIONAL { ?gndConcept schema:description ?desc_de . FILTER (LANG(?desc_de) = "de") }
    BIND(COALESCE(?desc_en, ?desc_de, "") as ?description)
}
