PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
CONSTRUCT {
  ?human wdt:P31 wd:Q5 .
  ?human rdfs:label ?name .
  ?human schema:description ?description .
}
WHERE {
  ?human wdt:P31 wd:Q5 .
  ?human wdt:P106/wdt:P279* wd:Q483501 .
  ?human rdfs:label ?name .
  ?human schema:description ?description .
  FILTER (LANG(?name) = "en")
  FILTER (LANG(?description) = "en")
}

